android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
FLIPPER_VERSION=0.212.0

# Play Store upload signing
MYAPP_UPLOAD_STORE_FILE=app/upload-keystore.jks
MYAPP_UPLOAD_KEY_ALIAS=upload
MYAPP_UPLOAD_STORE_PASSWORD=ProximaUpload@2026
MYAPP_UPLOAD_KEY_PASSWORD=ProximaUpload@2026
